theme: jekyll-theme-minimal
gem "github-pages", group: :jekyll_plugins
title: "Terra Incognita: diving into the subcortex"
description: "Virtual workshop on the subcortex, Amsterdam, March 1-3, 2021"
logo: poster-basic.png
show_downloads: false
